In [1]:
# Import all libraries 
import pandas as pd
import numpy as np 
import datetime
import matplotlib.pyplot as plt

In [2]:
def creating_x_mins_stock_price_table(x_mins):
    trump_tweets = pd.read_csv("trump_tweets_cleaned.csv")
    trump_tweets['date_new'] = pd.to_datetime(trump_tweets['date_new'])
    trump_tweets.rename(columns={"date_new": "tweet_datetime"}, inplace=True)
    trump_tweets.set_index('tweet_datetime', inplace=True, drop=False)
    trump_tweets.index.name = None
    trump_tweets = trump_tweets.between_time(datetime.time(4), datetime.time(20), include_start=True, include_end=True)

    
    stock_price = pd.read_csv("stock_price_cleaned.csv")
    stock_price.rename(columns={"DATE_TIME_M": "datetime", "PRICE": "price"}, inplace=True)
    stock_price['datetime']= pd.to_datetime(stock_price['datetime'])
    stock_price['date'] = stock_price['datetime'].apply(lambda x: x.date())
    
    end_of_day_prices = stock_price[stock_price['datetime'].apply(lambda x: x.time()) == datetime.time(20)]
    end_of_day_prices['datetime'] = end_of_day_prices['datetime'].apply(lambda x: x.date()) 
    end_of_day_prices.rename(columns={"price": "eod_price", "datetime": "eod_date"}, inplace=True)
    stock_price = stock_price.merge(end_of_day_prices, left_on='date', right_on='eod_date')
    stock_price.drop(columns=['date_x', 'date_y', 'eod_date'], inplace=True)
    
    
    stock_price[f"datetime_{x_mins}mins_before"] = stock_price["datetime"] - pd.Timedelta(f"{x_mins} min")

    stock_price_merged = stock_price.merge(stock_price, how='inner', left_on=[f"datetime_{x_mins}mins_before"], right_on=["datetime"])
    stock_price_merged.drop(columns=["datetime_y", f"datetime_{x_mins}mins_before_y"], inplace=True)
    stock_price_merged.rename(columns={"datetime_x": f"datetime_{x_mins}mins_after", "price_x": f"price_{x_mins}mins_after", f"datetime_{x_mins}mins_before_x": "datetime_now", "price_y": "price_now", "eod_price_x": "eod_price"}, inplace=True)
    stock_price_merged[f'{x_mins}mins_price_diff_abs'] = stock_price_merged[f'price_{x_mins}mins_after'] - stock_price_merged['price_now']
    stock_price_merged[f'{x_mins}mins_price_diff_perc'] = (stock_price_merged[f'price_{x_mins}mins_after'] - stock_price_merged['price_now']) / stock_price_merged['price_now']

    merged2 = trump_tweets.merge(stock_price_merged, how='inner', left_on=['tweet_datetime'], right_on=["datetime_now"])
    merged2.drop(columns=["datetime_now", "price_now"], inplace=True)
    
    return merged2

In [13]:
table_mins5 = creating_x_mins_stock_price_table(5)
table_mins6 = creating_x_mins_stock_price_table(6)
table_mins7 = creating_x_mins_stock_price_table(7)
table_mins8 = creating_x_mins_stock_price_table(8)
table_mins9 = creating_x_mins_stock_price_table(9)
table_mins10 = creating_x_mins_stock_price_table(10)

C:\anaconda\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [23]:
table_mins5

,id,cleaned_text,favorites,retweets,date,tweet_datetime,date_part,time_part,hour,year,...,tweet_length,compound,entity,entity_type,datetime_5mins_after,price_5mins_after,eod_price,eod_price_y,5mins_price_diff_abs,5mins_price_diff_perc
0,9.353400e+17,Thank you Rand!,42793,9125,2017-11-28 02:50:00,2017-11-28 10:50:00,2017-11-28,10:50:00,10,2017,...,16,0.4199,['Rand'],['ORG'],2017-11-28 10:55:00,261.085000,262.87,262.87,-0.015000,-0.000057
1,8.997980e+17,"Join me live from Fort Myer in Arlington, Virg...",36009,4891,2017-08-22 01:00:00,2017-08-22 09:00:00,2017-08-22,09:00:00,9,2017,...,54,0.2960,"['Fort Myer', 'Arlington', 'Virginia', 'âž¡']","['GPE', 'GPE', 'GPE', 'ORG']",2017-08-22 09:05:00,243.670000,245.44,245.44,0.000000,0.000000
2,8.939700e+17,Thank you Nicole!,43367,8275,2017-05-08 23:01:00,2017-05-09 07:01:00,2017-05-09,07:01:00,7,2017,...,18,0.4199,['Nicole'],['PERSON'],2017-05-09 07:06:00,239.920000,239.44,239.44,0.045000,0.000188
3,8.819770e+17,Thank you to Shawn Steel for the nice words on...,50956,7465,2017-03-07 20:44:00,2017-03-08 04:44:00,2017-03-08,04:44:00,4,2017,...,56,0.6486,['Shawn Steel'],['PERSON'],2017-03-08 04:49:00,236.913333,236.56,236.56,0.033333,0.000141
4,8.778460e+17,Great night in Iowa - special people. Thank you!,56446,8039,2017-06-22 11:11:00,2017-06-22 19:11:00,2017-06-22,19:11:00,19,2017,...,48,0.8622,"['night', 'Iowa']","['TIME', 'GPE']",2017-06-22 19:16:00,242.905000,242.84,242.84,0.025000,0.000103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2664,9.990960e+17,If the person placed very early into my campai...,78529,20098,2018-05-23 01:13:00,2018-05-23 09:13:00,2018-05-23,09:13:00,9,2018,...,513,0.6792,"['Collusion', 'Russia', 'Crooked Hillary', 'Be...","['ORG', 'GPE', 'PERSON', 'PERSON']",2018-05-23 09:18:00,271.100000,273.36,273.36,0.060000,0.000221
2665,9.874600e+17,So General Michael Flynnâ€™s life can be totally...,93569,25259,2018-04-20 10:34:00,2018-04-20 18:34:00,2018-04-20,18:34:00,18,2018,...,539,-0.6689,"['Michael Flynn', 'Shadey James Comey', 'Leak'...","['PERSON', 'PERSON', 'PERSON', 'ORDINAL', 'GPE...",2018-04-20 18:39:00,266.866667,266.61,266.61,0.046667,0.000175
2666,9.870960e+17,"My thoughts, prayers and condolences are with ...",62645,16081,2018-04-19 22:30:00,2018-04-20 06:30:00,2018-04-20,06:30:00,6,2018,...,447,0.6900,"['two', '@GCSOFlorida', 'HEROES', 'today', 'Sa...","['CARDINAL', 'ORG', 'ORG', 'DATE', 'PERSON', '...",2018-04-20 06:35:00,268.715000,266.61,266.61,0.095000,0.000354
2667,9.863570e+17,Todayâ€™s Court decision means that Congress mus...,56749,12426,2018-04-17 21:34:00,2018-04-18 05:34:00,2018-04-18,05:34:00,5,2018,...,357,-0.9493,"['Today', 'Congress', 'Congress', 'House', 'Se...","['DATE', 'ORG', 'ORG', 'ORG', 'ORG', 'ORG']",2018-04-18 05:39:00,270.600000,270.39,270.39,0.000000,0.000000
2668,9.791090e+17,I am pleased to announce that I intend to nomi...,66173,13399,2018-03-28 21:31:00,2018-03-29 05:31:00,2018-03-29,05:31:00,5,2018,...,305,0.9565,"['Ronny L. Jackson', 'MD', 'Veterans Affairs',...","['PERSON', 'ORG', 'ORG', 'ORG', 'PERSON', 'ORG...",2018-03-29 05:36:00,260.997143,263.15,263.15,0.014286,0.000055

In [41]:
x_5 = table_mins5[['favorites','retweets', 'tweet_length', 'compound']].values
y_5 = table_mins5['5mins_price_diff_abs'].values

In [42]:
from sklearn import linear_model

In [50]:
regr_5 = linear_model.LinearRegression()
regr_5.fit(x_5, y_5)

LinearRegression()

In [59]:
from sklearn import model_selection, metrics, preprocessing

for i in range(5,11):
    table = eval("table_mins" + str(i))
    x = table[['compound']].values
#     x = table[['compound']].values
    #y = table[str(i) + 'mins_price_diff_abs'].values
    y = table['eod_price_y'].values
    x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size = 0.2, random_state = 2020)

#     x_train_scaled = preprocessing.scale(x_train)
#     y_train_scaled = preprocessing.scale(y_train)
#     x_test_scaled = preprocessing.scale(x_test)
#     y_test_scaled = preprocessing.scale(y_test)
    
    regr = linear_model.LinearRegression()
    regr.fit(x_train, y_train)
    print('Metrics for stock price ' + str(i) + ' mins after tweet')
    print('R^2 score: %.2f' % regr.score(x_test, y_test))

    y_pred = regr.predict(x_test)
    print(metrics.explained_variance_score(y_test, y_pred))
    print(metrics.mean_absolute_error(y_test, y_pred))
    print(metrics.mean_squared_error(y_test, y_pred))
    
    
    print('-' * 64)

Metrics for stock price 5 mins after tweet
R^2 score: 0.00
0.0011895963771090257
15.143010804659419
303.6806528269175
----------------------------------------------------------------
Metrics for stock price 6 mins after tweet
R^2 score: 0.00
0.0036078934243238825
14.682097278302269
285.82969828541815
----------------------------------------------------------------
Metrics for stock price 7 mins after tweet
R^2 score: 0.00
0.0011468845907703917
15.055576432484232
296.10729422594983
----------------------------------------------------------------
Metrics for stock price 8 mins after tweet
R^2 score: 0.00
0.005905335181714211
15.147064440823073
304.47820425671426
----------------------------------------------------------------
Metrics for stock price 9 mins after tweet
R^2 score: 0.00
0.0019168901782308234
15.305114895795043
308.3550620245874
----------------------------------------------------------------
Metrics for stock price 10 mins after tweet
R^2 score: 0.01
0.006640098797671357
14.666849315841077
286.24484946566145
----------------------------------------------------------------

In [54]:
import matplotlib.pyplot as plt

x = table_mins5[['favorites','retweets', 'tweet_length', 'compound']]
print(x.corr())

              favorites  retweets  tweet_length  compound
favorites      1.000000  0.893992      0.143862 -0.107690
retweets       0.893992  1.000000      0.145096 -0.163181
tweet_length   0.143862  0.145096      1.000000 -0.088696
compound      -0.107690 -0.163181     -0.088696  1.000000